### ISSUE TITLE
User Story - Memory-match minigame

### ISSUE THREAD

**Issue by JL-14** [stephendawsondev/HalloweenHackathon#9]
Story

As a user, I can play a memory-match minigame so that I can get some variety from the overall app.

Acceptance Criteria
-Memory-match game works on both mobile and desktop
-The cards in the game should be easily selectable with mouse, keyboard, and on touchscreen
-The cards and colour scheme should be in line with the Halloween and general theme

Tasks
 -Create a wireframe for the game
 -Source image(s) for the game
 -Create game code
 -Source sound effects for the game
 -Source special effects  for the game

**Comment by stephendawsondev** [comment]
Pretty much done, just need to add local storage to say when the game has been complete.
